// styles
import styles from '../styles/Home.module.css';
// components
import Banner from '../components/banner/Banner';
import Card from '../components/card/Card';
// next
import Head from 'next/head';
import Image from 'next/image';
// data
import coffeStoresData from '../data/coffe-stores-data.json';

export async function getStaticProps(context) {
  return {
    props: {
      coffeStores: coffeStoresData,
    },
  };
}
export default function Home(props) {
  const { coffeStores } = props;
  const handleBannerBtnClick = () => {
    console.log('clicked');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner onBannerBtnClick={handleBannerBtnClick} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} />
        </div>
        <h2>Test</h2>
        <div className={styles.cardLayout}>
          {coffeStores.map((coffeStore) => (
            <Card key={coffeStore.id} row={coffeStore} />
          ))}
        </div>
      </main>
    </div>
  );
}
