// React
import { useEffect, useState, useContext } from 'react';
// styles
import styles from '../styles/Home.module.css';
// components
import Banner from '../components/banner/Banner';
import Card from '../components/card/Card';
// next
import Head from 'next/head';
import Image from 'next/image';
// data
import { GetCoffeStores } from '../lib/GetCoffeStore';
import useGetLocation from '../lib/useGetLocation';
// Context
import { SotresContext, ACTION_TYPES } from '../context/store-context';
// ------------------------------------------------

export async function getStaticProps() {
  const coffeStores = await GetCoffeStores();
  return {
    props: {
      coffeStores,
    },
  };
}

// ------------------------------------------------

export default function Home(props) {
  const { dispatch, state } = useContext(SotresContext);
  const { handleGetLocation, loading } = useGetLocation();
  const { coffeStores } = props;

  const handleBannerBtnClick = () => {
    handleGetLocation();
  };

  useEffect(() => {
    async function fetchData() {
      if (state.lattlong) {
        try {
          const coffeStores = await GetCoffeStores(state.lattlong);
          dispatch({
            type: ACTION_TYPES.SET_COFFE_STORES,
            payload: coffeStores,
          });
        } catch (error) {
          console.log(error);
        }
      }
    }
    fetchData();
  }, [state.lattlong]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner onBannerBtnClick={handleBannerBtnClick} loading={loading} />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" alt="mainImg" width={700} height={400} />
        </div>

        {state.coffeStores.length > 0 && (
          <>
            <h2 className={styles.mainTitle}>Nerby Stores</h2>
            <div className={styles.cardLayout}>
              {state.coffeStores.map((coffeStore, idx) => (
                <Card key={idx} row={coffeStore} />
              ))}
            </div>
          </>
        )}

        <h2 className={styles.mainTitle}>Amman Stores</h2>
        <div className={styles.cardLayout}>
          {coffeStores.map((coffeStore, idx) => (
            <Card key={idx} row={coffeStore} />
          ))}
        </div>
      </main>
    </div>
  );
}
